### ISSUE TITLE
Error in the client 

### ISSUE THREAD

**Issue by jedipython** [nftstorage/python-client#4]
Error in the python client after the last update on nft.storage
TypeError: _from_openapi_data() missing 1 required positional argument: 'last_change'
What is required to be specified in this argument?

**Comment by dchoi27** [comment]
Duplicate of https://github.com/nftstorage/nft.storage/issues/1775

**Comment by alanshaw** [comment]
@jedipython any chance you can send a PR to fix...maybe regenerating this using an updated schema will help - https://github.com/nftstorage/nft.storage/blob/main/client-gen.sh

**Comment by dchoi27** [comment]
Closing this since we're not supporting this auto-generated Python client
